micronaut:
    application:
        name: bookrecommendation
    server:
        port: 8080
endpoints:
  health:
    enabled: true
    sensitive: false
#tag::zipkin[]
tracing:
    zipkin:
        enabled: true
        sampler:
            probability: 1 # <1>
#end::zipkin[]